spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/springjwt
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: mariadb
      database-platform: org.hibernate.dialect.MariaDB103Dialect
